# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool: IIS-Pool

variables:
  buildConfiguration: 'Release'
  projectName: 'WebApplication1'
  websiteName: 'WebApplication'
  appPoolName: 'WebApplication'
  Logging.LogLevel.Default: "Warning"
  system.debug: "true"
  ASPNETCORE_ENVIRONMENT: "Beta"
  AdminUserName: "Testing"
  AdminPassword: "Pwd"

stages:
- stage: 'Build'
  displayName: 'Build'
  jobs:
     - job: 
       steps:  
        - task: DotNetCoreCLI@2
          displayName: 'dotnet restore'
          inputs:
            command: 'restore'
            projects: '*.sln'

        - task: DotNetCoreCLI@2
          displayName: Build
          inputs:
            command: 'build'
            projects: '*.sln'
            arguments: '--configuration Release /p:TransformWebConfigEnabled=false /p:AutoParameterizationWebConfigConnectionStrings=false /p:MarkWebConfigAssistFilesAsExclude=false /p:ProfileTransformWebConfigEnabled=false /p:IsTransformWebConfigDisabled=true'

            #arguments: --configuration Release

        # - task: DotNetCoreCLI@2
        #   displayName: Test
        #   inputs:
        #     command: test
        #     projects: '*.sln'
        #     arguments: '--configuration $(BuildConfiguration)'
       
        - task: DotNetCoreCLI@2
          displayName: 'Publish the project - $(buildConfiguration)'
          inputs:
            command: 'publish'
            projects: '**/*1.csproj'
            publishWebProjects: false
            arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
            zipAfterPublish: false

        - task: FileTransform@2
          displayName: 'Apply File Transformations on web.config'
          inputs:
            folderPath: '$(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
            xmlTransformationRules: '-transform **\*.Release.config -xml **\*.config'
            xmlTargetFiles: '**/web.config'
        
        - powershell: |
            $webConfig = Get-Content "$(Build.ArtifactStagingDirectory)/$(buildConfiguration)/$(projectName)/web.config"
            $webConfig = $webConfig -replace '__ASPNETCORE_ENVIRONMENT__', '$(ASPNETCORE_ENVIRONMENT)'
            $webConfig | Set-Content "$(Build.ArtifactStagingDirectory)/$(buildConfiguration)/$(projectName)/web.config"
          displayName: 'Update web.config with environment variables'

        - publish: '$(Build.ArtifactStagingDirectory)'
          artifact: drop

- stage: 'Dev'
  displayName: 'Dev'
  dependsOn: 'Build'
  #condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
   - deployment: Dev
     displayName: Dev
     environment: 'IIS-Dev.EC2AMAZ-E27F7CA'   
     variables:
     - name: websitePhysicalPath
       value: '%SystemDrive%\inetpub\wwwroot\$(websiteName)'
     - name: ASPNETCORE_ENVIRONMENT
       value: 'BETA'
     - name: system.debug
       value: 'true'

     strategy:
      runOnce:
        deploy:
          steps: 
          - task: FileTransform@2
            inputs:
              folderPath: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/$(projectName)'
              xmlTransformationRules: 
              xmlTargetFiles: '**/web.config'

          - task: IISWebAppManagementOnMachineGroup@0
            inputs:            
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'CreateOrUpdateWebsite'
              WebsiteName: '$(websiteName)'
              WebsitePhysicalPath: '$(websitePhysicalPath)'
              WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
              CreateOrUpdateAppPoolForWebsite: true
              AppPoolNameForWebsite: '$(appPoolName)'
              DotNetVersionForWebsite: 'No Managed Code'
              PipeLineModeForWebsite: 'Integrated'
              AppPoolIdentityForWebsite: 'ApplicationPoolIdentity'
              AddBinding: true
              Bindings: |
                  {
                      bindings:[
                          {
                              "protocol":"http",
                              "ipAddress":"All Unassigned",
                              "port":"85",
                              "sslThumbprint":"",
                              "sniFlag":false
                          }
                      ]
                  }
          - task: IISWebAppManagementOnMachineGroup@0
            inputs:
              IISDeploymentType: 'IISVirtualDirectory'
              ParentWebsiteNameForVD: '$(websiteName)'
              VirtualPathForVD: '/TestVirPath'
              PhysicalPathForVD: '%SystemDrive%\inetpub\wwwroot'
              VDPhysicalPathAuth: 'VDWindowsAuth'
              VDAuthUserName: 'TestUser'
              VDAuthUserPassword: 'TestPass'
          - task: IISWebAppDeploymentOnMachineGroup@0
            inputs:
              WebSiteName: '$(websiteName)'
              Package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/$(projectName)'
              XmlVariableSubstitution: true
              JSONFiles: '**\appsettings.json'
